"use client";

import type { Metadata } from "next";
import { Amplify } from "aws-amplify";
import { Authenticator } from "@aws-amplify/ui-react";
import "@aws-amplify/ui-react/styles.css";
import "./globals.css";

// Amplify config is injected at build time from amplify_outputs.json
// (generated by `ampx sandbox`). In development, copy the generated file here.
let amplifyConfig: Record<string, unknown> = {};
try {
  // eslint-disable-next-line @typescript-eslint/no-var-requires
  amplifyConfig = require("../../amplify_outputs.json");
} catch {
  console.warn("amplify_outputs.json not found — run `npx ampx sandbox` first");
}

if (Object.keys(amplifyConfig).length > 0) {
  Amplify.configure(amplifyConfig as any);
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Authenticator>
          {({ signOut, user }) => (
            <main>
              <nav className="navbar">
                <span className="navbar-title">Edge Digital Ops Workshop</span>
                <span className="navbar-user">{user?.signInDetails?.loginId}</span>
                <button onClick={signOut} className="navbar-signout">Sign out</button>
              </nav>
              {children}
            </main>
          )}
        </Authenticator>
      </body>
    </html>
  );
}
